---
baseURL: "/"
algolia:
  index: jwanp
  appID: 6QK332EH1T
---

baseURL: 'http://jwanp.github.io'
theme: LoveIt
title: Joohwan's blog
languageCode: en
languageName: English
googleAnalytics: G-DZ2VH32QXR
paginate: 12
enableRobotsTXT: true


author:
  name: 박주환
  email: ''
  link: ''


params:
  defaultTheme: auto
  gitRepo: ''
  dateFormat: '2006-01-02'
  title: Hello this is title
  description: Hello this is description
  images: []
  header:
    desktopMode: fixed
    mobileMode: auto
    title:
      logo: ''
      name: Joohwan's dev blog
      pre: ''
      post: ''
      typeit: false
  search:
    enable: true
    type: algolia
    contentLength: 4000
    placeholder: ''
    maxResultLength: 10
    snippetLength: 30
    highlightTag: em
    absoluteURL: false
    algolia:
      index: jwanp
      appID: 6QK332EH1T
      searchKey: 79b39b96ee30ec1c39a4bf1a4037c605
  analytics:
    enable: true
    google:
      id: G-DZ2VH32QXR
      anonymizeIP: true
  home:
    rss: 10
    profile:
      enable: true
      gravatarEmail: ''
      avatarURL: /images/avatar.png
      title: ''
      subtitle: Hello world!
      typeit: true
      social: true
      disclaimer: ''
    posts:
      enable: true
      paginate: 6
      defaultHiddenFromHomePage: false
  social:
    GitHub: jwanp
    Email: joohwan726@naver.com
    Steam: Jwan_Park
    Kaggle: joohwan456
  page:
    hiddenFromHomePage: false
    hiddenFromSearch: false
    code:
      copy: true
    share:
      enable: true
      Twitter: true
      Facebook: true
      Linkedin: true
      Blogger: true
    comment:
      enable: true
      utterances:
        enable: true
        repo: jwanp/blog-comment
        issueTerm: pathname
        label: Comment
  seo:
    image: >-
      https://user-images.githubusercontent.com/77142334/227780652-4a867037-5843-4d78-b5e7-9c27f6203e23.png
    thumbnailUrl: >-
      https://user-images.githubusercontent.com/77142334/227780652-4a867037-5843-4d78-b5e7-9c27f6203e23.png
menu:
  main:
    - weight: 1
      identifier: posts
      pre: ''
      post: ''
      name: Posts
      url: /posts/
      title: ''
    - weight: 2
      identifier: tags
      pre: ''
      post: ''
      name: Tags
      url: /tags/
      title: ''
    - weight: 3
      identifier: categories
      pre: ''
      post: ''
      name: Categories
      url: /categories/
      title: ''
    - weight: 4
      identifier: personal page
      pre: ''
      post: ''
      name: About
      url: /about/
      title: ''
markup:
  highlight:
    noClasses: false
